### ISSUE TITLE
Development of tired points/ Turning points

### ISSUE THREAD

**Issue by peerzadaaabid** [MarcoSpoerl/simply-pace#3]
Hi
The thing I want to implement here is that
The app should  make a user able to choose number of ''tired points''.
By tired points I mean the points where a soul will take a deep breathe(Rest).
Later on the app should calculate the pace which should be displayed in the slots.
By slots I mean , distance between the two tired points.
Thanks

**Comment by MarcoSpoerl** [comment]
Thanks for your idea. Unfortunately, I won't implement any significant changes for the app, as this dilutes my vision of a very simple pace calculator.
